"""create attempts table

Revision ID: 465ddcba0774
Revises: 7be4150e3e41
Create Date: 2026-07-15 13:23:05.892663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465ddcba0774'
down_revision: Union[str, Sequence[str], None] = '7be4150e3e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('used_language', sa.Enum('PYTHON', 'JAVA', 'C_PLUS_PLUS', 'JAVASCRIPT', 'C', 'C_SHARP', 'GO', 'RUBY', 'RUST', 'TYPESCRIPT', 'PHP', 'KOTLIN', 'SWIFT', 'SCALA', 'DART', 'ELIXIR', 'ERLANG', 'R', 'MATLAB', 'PERL', 'HASKELL', 'CANGJIE', 'Other', name='language'), nullable=False),
    sa.Column('code_source', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('time_complexity', sa.Enum('CONSTANT', 'LOGARITHMIC', 'LINEAR', 'LINEAR_LOG', 'QUADRATIC', 'CUBIC', 'EXPONENTIAL', 'FACTORIAL', name='complexity'), nullable=False),
    sa.Column('space_complexity', sa.Enum('CONSTANT', 'LOGARITHMIC', 'LINEAR', 'LINEAR_LOG', 'QUADRATIC', 'CUBIC', 'EXPONENTIAL', 'FACTORIAL', name='complexity'), nullable=False),
    sa.Column('status', sa.Enum('SOLVED', 'ATTEMPTED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    # ### end Alembic commands ###
